version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "awscallout"
s3_bucket = "cyruswong-sam-repo"
s3_prefix = "awscallout"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides="InstanceId=ca26ad62-6ec2-42be-b72d-113ea7b05a85 ContactFlowId=ac34a179-86bf-4a02-ba8f-6436c789d199 SourcePhoneNumber=+448081695856"