version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "awscallout"
# s3_bucket = awscalloutchange-this-to-get-a-unique-source-bucket
s3_bucket = "cyruswong-sam-repo"
s3_prefix = "awscallout"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides="InstanceId=242762ab-3f7e-47bc-8880-61a10fa612e1 ContactFlowId=a6a44841-916a-4160-9a8d-72036924add8 SourcePhoneNumber=+18146552012"