AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  callout
Parameters:
  InstanceArn:
    Type: String
  ContactFlowArn:
    Type: String
  SourcePhoneNumber:
    Type: String
Globals:
  Function:
    Timeout: 30
    Tracing: Active
    Runtime: python3.7  
Resources:
  CalloutFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: send_call.lambda_handler
      CodeUri: call_out/
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
               - connect:StartOutboundVoiceContact
              Resource: !Sub ${InstanceArn}/*
            - Effect: Allow
              Action:
               - states:SendTaskSuccess 
              Resource: !Ref CalloutStateMachine      
      Environment:
        Variables:
          ContactFlowArn: !Ref ContactFlowArn
          SourcePhoneNumber: !Ref SourcePhoneNumber
          AsynCalloutQueueUrl: !Ref AsynCalloutQueue
      Events:
        CallSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt AsynCalloutQueue.Arn
            BatchSize: 1
            
  LibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: lib
      CompatibleRuntimes:
        - python3.7
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Delete  
      
  CalloutSQSQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: start_call_out_flow.lambda_handler
      CodeUri: call_out/
      Layers:
        - !Ref LibLayer     
      ReservedConcurrentExecutions: 1
      Policies:
        - StepFunctionsExecutionPolicy:
            StateMachineName:
              !GetAtt CalloutStateMachine.Name
      Environment:
        Variables:
          CallSqsQueueUrl: !Ref CallSqsQueue
          CalloutStateMachineArn: !Ref CalloutStateMachine
          ResponseHanlderFunctionArn: !GetAtt ResponseHanlderFunction.Arn
      Events:
        CallSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt CallSqsQueue.Arn
            BatchSize: 1

  ResponseHanlderFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: response_handler.lambda_handler
      CodeUri: call_out/
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
               - states:SendTaskSuccess
              Resource: !Ref CalloutStateMachine
              
  CallSqsQueue:
    Type: AWS::SQS::Queue
    Properties: 
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt CallDeadLetterQueue.Arn
        maxReceiveCount: 1
  CallDeadLetterQueue: 
    Type: AWS::SQS::Queue
    
  AsynCalloutQueue:
    Type: AWS::SQS::Queue
    Properties: 
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt AsynCalloutDeadLetterQueue.Arn
        maxReceiveCount: 1
  AsynCalloutDeadLetterQueue: 
    Type: AWS::SQS::Queue

  CallResultDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String  
        
  CalloutStatesExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt AsynCalloutQueue.Arn
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !GetAtt CallResultDynamoDBTable.Arn
                
  CalloutStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "Reading messages from an SQS queue and iteratively processing each message.",
              "StartAt": "Start",
              "States": {
                "Start":{
                  "Type": "Pass",    
                  "Next": "Process Call Messages"
                },
                "Process Call Messages": {
                  "Type": "Map",
                  "Next": "Finish",
                  "InputPath": "$",
                  "ItemsPath": "$",
                  "Iterator": {
                    "StartAt": "Callout with AWS Connect",
                    "States": {
                      "Callout with AWS Connect": {
                        "Type": "Task",
                        "Resource": "arn:aws:states:::sqs:sendMessage.waitForTaskToken",
                        "TimeoutSeconds": 30,
                        "Parameters": {
                          "QueueUrl": "${AsynCalloutQueue}",
                          "MessageBody": {
                              "Message.$":"$",
                              "TaskToken.$": "$$.Task.Token"
                           }
                        },
                        "Catch": [ {
                            "ErrorEquals": [ "States.Timeout" ],
                            "ResultPath": null,
                            "Next": "Call Timeout"
                         } ],
                        "Next": "Save call result"
                      },
                      "Call Timeout": {
                        "Type": "Pass",
                        "ResultPath": null,
                        "Next": "Save call result"
                      }, 
                      "Save call result": {
                        "Type": "Task",
                        "Resource": "arn:aws:states:::dynamodb:putItem",
                        "Parameters": {
                          "TableName": "${CallResultDynamoDBTable}",
                          "Item": {
                            "id": {"S.$": "$.id"},
                            "username": {"S.$": "$.username"},
                            "message": {"S.$": "$.message"},
                            "phone_number": {"S.$": "$.phone_number"},
                            "question_type": {"S.$": "$.question_type"},
                            "status": {"S.$": "$.status"},
                            "answer": {"S.$": "$.answer"},
                            "error": {"S.$": "$.error"}
                          }
                        },
                        "ResultPath": "$.Result",
                        "End": true
                      }
                    }
                  }
                },
                "Finish": {
                  "Type": "Succeed"
                }
              }
            }                       
          - 
            AsynCalloutQueue: !Ref AsynCalloutQueue
            CallResultDynamoDBTable: !Ref CallResultDynamoDBTable
      RoleArn: !GetAtt CalloutStatesExecutionRole.Arn
      
      
Outputs:
  CallSqsQueue:
    Description: "Call Out Queue ARN"
    Value: !GetAtt CallSqsQueue.Arn

