AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  callout

  Sample SAM Template for callout
Parameters:
  ContactFlowId:
    Type: String
  InstanceId:
    Type: String
  SourcePhoneNumber:
    Type: String
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180
    Tracing: Active

Resources:
  CalloutFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: call_out/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
               - connect:StartOutboundVoiceContact
              Resource: "*"
      Environment:
        Variables:
          ContactFlowId: !Ref ContactFlowId
          InstanceId: !Ref InstanceId
          SourcePhoneNumber: !Ref SourcePhoneNumber

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CalloutFunction:
    Description: "Call Out Lambda Function ARN"
    Value: !GetAtt CalloutFunction.Arn
  CalloutFunctionIamRole:
    Description: "Implicit IAM Role created for Call Out function"
    Value: !GetAtt CalloutFunctionRole.Arn
