AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  callout
Parameters:
  ContactFlowArn:
    Type: String
  SourcePhoneNumber:
    Type: String
Globals:
  Function:
    Timeout: 180
    Tracing: Active
    Runtime: python3.7  
Resources:
  CalloutFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: send_call.lambda_handler
      CodeUri: call_out/
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
               - connect:StartOutboundVoiceContact
              Resource: "*"
      Environment:
        Variables:
          ContactFlowArn: !Ref ContactFlowArn
          SourcePhoneNumber: !Ref SourcePhoneNumber

  InputTransformFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: input_transform.lambda_handler
      CodeUri: call_out/
      
  CalloutSQSQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: start_call_out_flow.lambda_handler
      CodeUri: call_out/
      Timeout: 30
      Policies:
        - StepFunctionsExecutionPolicy:
            StateMachineName:
              !GetAtt [ CalloutStateMachine, Name ]
      Environment:
        Variables:
          CallSqsQueueUrl: !Ref CallSqsQueue
          CalloutStateMachineArn: !Ref CalloutStateMachine      
      Events:
        CallSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt CallSqsQueue.Arn
            BatchSize: 1
            
  CallSqsQueue:
    Type: AWS::SQS::Queue
    Properties: 
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt [ CallDeadLetterQueue, Arn ]
        maxReceiveCount: 1
  CallDeadLetterQueue: 
    Type: AWS::SQS::Queue

  CalloutStatesExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  CalloutStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "Reading messages from an SQS queue and iteratively processing each message.",
              "StartAt": "Input Transform",
              "States": {
                "Input Transform":{
                  "Type": "Task",
                  "Resource": "${InputTransformFunction}",
                  "Next": "Process Call Messages"
                },
                "Process Call Messages": {
                  "Type": "Map",
                  "Next": "Finish",
                  "InputPath": "$",
                  "ItemsPath": "$.items",
                  "Iterator": {
                    "StartAt": "Callout with AWS Connect",
                    "States": {
                      "Callout with AWS Connect": {
                        "Type": "Task",
                        "Resource": "${CalloutFunction}",
                        "End": true
                      }
                    }
                  }
                },
                "Finish": {
                  "Type": "Succeed"
                }
              }
            }            
          - 
            CalloutFunction: !GetAtt [ CalloutFunction, Arn ]
            InputTransformFunction: !GetAtt [ InputTransformFunction, Arn ]
      RoleArn: !GetAtt [ CalloutStatesExecutionRole, Arn ]
      
      
Outputs:
  CallSqsQueue:
    Description: "Call Out Queue ARN"
    Value: !GetAtt CallSqsQueue.Arn

